# Basic Site Settings
locale                   : "en-US"
title                    : "Tu Dao — Research Page"
title_separator          : "-"
name                     : &name "Dao Duc Tu"
description              : &description "Postdoctoral Researcher in Mathematics & Biology"
url                      : "https://daoductu112.github.io"  # root site
baseurl                  : ""  # leave empty since we use root
repository               : "daoductu112/daoductu112.github.io"

# Site Author
author:
  avatar           : "profile.png"
  name             : "Dao Duc Tu"
  bio              : "Postdoctoral Scientist at Genome Institute of Singapore. Interested in combinatorics, bioinformatics, and chromatin organization."
  location         : "Singapore"
  employer         : "Genome Institute of Singapore"
  email            : "your.email@domain.com"

  # Academic websites
  googlescholar    : "https://scholar.google.com/citations?user=PS_CX0AAAAAJ"
  orcid            : "https://orcid.org/XXXX-XXXX-XXXX-XXXX"   # put your real ORCID
  pubmed           : "https://pubmed.ncbi.nlm.nih.gov/?term=Dao+DT" # adjust search
  researchgate     : "https://www.researchgate.net/profile/Dao-Tu" # if you use RG
  github           : "daoductu112"

  # Social media
  linkedin         : "https://www.linkedin.com/in/yourprofile/" # if you use
  twitter          : ""  # leave blank if not using
